# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: xserver
version: "0.1.21"
slug: xserver
description: X Server
url: "https://github.com/LaneaLucy/haos-addons/tree/main/xserver"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
init: false
audio: true
full_access: true
#ports:
#  6680/tcp: 6680
#webui: http://[HOST]:[PORT:6680]/
map:
  - config
  - share:rw
  - media
options:
  system_packages: []
  python_packages: []
  xinit_command: "firefox-esr --kiosk http://localhost:8123/"
  x_options: "-nolisten tcp"
schema:
  system_packages:
    - str
  python_packages:
    - str
  xinit_command: str
  x_options: str

image: ghcr.io/lanealucy/haos-addon-xserver-{arch}
